gstaycar:
    resource: "@GstaycarBundle/Controller/"
    type:     annotation
    prefix:   /rent

gstayforum:
    resource: "@GstayforumBundle/Controller/"
    type:     annotation
    prefix:   /forum

gstayguesthost:
    resource: "@GstayguesthostBundle/Controller/"
    type:     annotation
    prefix:   /hostguest

gstayhotel:
    resource: "@GstayhotelBundle/Controller/"
    type:     annotation
    prefix:   /hotel

gstayevent:
    resource: "@GstayeventBundle/Controller/"
    type:     annotation
    prefix:   /event

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile